enum CaseEventsAPI {
  CREATE_CLAIM = 'CREATE_CLAIM',
  CREATE_CLAIM_SPEC = 'CREATE_CLAIM_SPEC',
  MANAGE_CONTACT_INFORMATION = 'MANAGE_CONTACT_INFORMATION',
  ADD_OR_AMEND_CLAIM_DOCUMENTS = 'ADD_OR_AMEND_CLAIM_DOCUMENTS',
  NOTIFY_DEFENDANT_OF_CLAIM = 'NOTIFY_DEFENDANT_OF_CLAIM',
  NOTIFY_DEFENDANT_OF_CLAIM_DETAILS = 'NOTIFY_DEFENDANT_OF_CLAIM_DETAILS',
  AMEND_PARTY_DETAILS = 'AMEND_PARTY_DETAILS',
  ACKNOWLEDGE_CLAIM = 'ACKNOWLEDGE_CLAIM',
  INFORM_AGREED_EXTENSION_DATE = 'INFORM_AGREED_EXTENSION_DATE',
  DEFENDANT_RESPONSE = 'DEFENDANT_RESPONSE',
  CLAIMANT_RESPONSE = 'CLAIMANT_RESPONSE',
  INITIATE_GENERAL_APPLICATION = 'INITIATE_GENERAL_APPLICATION',
}

export default CaseEventsAPI;
