// Case states from ccd-definition/State.json that the unspecified journey checks
enum CaseStates {
  CASE_ISSUED = 'CASE_ISSUED',
  AWAITING_CASE_DETAILS_NOTIFICATION = 'AWAITING_CASE_DETAILS_NOTIFICATION',
  AWAITING_RESPONDENT_ACKNOWLEDGEMENT = 'AWAITING_RESPONDENT_ACKNOWLEDGEMENT',
  AWAITING_APPLICANT_INTENTION = 'AWAITING_APPLICANT_INTENTION',
  // Shown in XUI as "Case Proceeds Offline"
  PROCEEDS_IN_HERITAGE_SYSTEM = 'PROCEEDS_IN_HERITAGE_SYSTEM',
}

export default CaseStates;
