module.exports = {
  name: 'Transfer Case Offline',
  type: 'transferCaseOfflineM',
  task_title: 'Transfer Case Offline',
  location_name: '',
  location: '420219',
  execution_type: 'Case Management Task',
  jurisdiction: 'CIVIL',
  region: '2',
  permissions: { values: ['Read', 'Own', 'Manage', 'Cancel', 'Complete', 'Claim', 'Assign', 'Unassign'] },
  description: '[Transfer Case Offline](/cases/case-details/${[CASE_REFERENCE]}/)',
  case_type_id: 'CIVIL',
  case_name: 'Test Inc',
  case_category: 'Civil',
  created_date: '2025-03-10T13:05:14+0000',
  security_classification: 'PUBLIC',
  task_state: 'unassigned',
  auto_assigned: false,
  location_id: '420219',
  work_type_id: 'routine_work',
  work_type_label: 'Hearing work',
  role_category: 'ADMIN',
};
