enum JudicialDecision {
  MAKE_AN_ORDER = 'MAKE_AN_ORDER',
  FREE_FORM_ORDER = 'FREE_FORM_ORDER',
  REQUEST_MORE_INFO = 'REQUEST_MORE_INFO',
  LIST_FOR_A_HEARING = 'LIST_FOR_A_HEARING',
  MAKE_ORDER_FOR_WRITTEN_REPRESENTATIONS = 'MAKE_ORDER_FOR_WRITTEN_REPRESENTATIONS',
};

export default JudicialDecision;