enum ClaimTypeUnspec {
  PERSONAL_INJURY = 'PERSONAL_INJURY',
  CLINICAL_NEGLIGENCE = 'CLINICAL_NEGLIGENCE',
  PROFESSIONAL_NEGLIGENCE = 'PROFESSIONAL_NEGLIGENCE',
  BREACH_OF_CONTRACT = 'BREACH_OF_CONTRACT',
  CONSUMER = 'CONSUMER',
  CONSUMER_CREDIT = 'CONSUMER_CREDIT',
  DAMAGES_AND_OTHER_REMEDY = 'DAMAGES_AND_OTHER_REMEDY',
  OTHER = 'OTHER',
}

export default ClaimTypeUnspec;
