enum GaTypeLr {
  ADJOURN_HEARING = 'ADJOURN_HEARING',
  AMEND_A_STMT_OF_CASE ='AMEND_A_STMT_OF_CASE',
  EXTEND_TIME = 'EXTEND_TIME',
  RELIEF_FROM_SANCTIONS = 'RELIEF_FROM_SANCTIONS',
  SET_ASIDE_JUDGEMENT = 'SET_ASIDE_JUDGEMENT',
  STAY_THE_CLAIM = 'STAY_THE_CLAIM',
  STRIKE_OUT = 'STRIKE_OUT',
  SUMMARY_JUDGEMENT = 'SUMMARY_JUDGEMENT',
  UNLESS_ORDER = 'UNLESS_ORDER',
  VARY_ORDER = 'VARY_ORDER',
  SETTLE_BY_CONSENT = 'SETTLE_BY_CONSENT',
  VARY_PAYMENT_TERMS_OF_JUDGMENT = 'VARY_PAYMENT_TERMS_OF_JUDGMENT',
  OTHER = 'OTHER'
};

export default GaTypeLr;