enum HearingNoticeScenario {
  SKIP_NOTICE_CURRENT_VERSION_NOTIFIED,
  NOTIFY_CURRENT_VERSION_MULTI_HMC_RESPONSES,
  GENERATE_NOTICE_RELISTED_VERSION,
  ACKNOWLEDGE_HEARING_WITHOUT_NOTICE,
  AVOID_DUPLICATE_NOTICE_WITHOUT_GENERATING_NOTICE,
  GENERATE_NOTICE_PARTIAL_HMC_RESPONSE,
};

export default HearingNoticeScenario;