enum RecipientRoleType {
  ADMIN = 'ADMIN',
  COURT_STAFF = 'COURT_STAFF',
  DISTRICT_JUDGE = 'DISTRICT_JUDGE',
  CIRCUIT_JUDGE = 'CIRCUIT_JUDGE',
  LEGAL_ADVISOR = 'LEGAL_ADVISOR',
  WELSH_LANGUAGE_UNIT = 'WELSH_LANGUAGE_UNIT'
}

export default RecipientRoleType;