enum GaCaseState {
  AWAITING_APPLICATION_PAYMENT = 'AWAITING_APPLICATION_PAYMENT',
  AWAITING_RESPONDENT_RESPONSE = 'AWAITING_RESPONDENT_RESPONSE',
  APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION = 'APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION',
  AWAITING_ADDITIONAL_INFORMATION = 'AWAITING_ADDITIONAL_INFORMATION',
  LISTING_FOR_A_HEARING = 'LISTING_FOR_A_HEARING',
  HEARING_SCHEDULED = 'HEARING_SCHEDULED'
}

export default GaCaseState;
