civil-service:
  java:
    ingressHost: ${SERVICE_NAME}.preview.platform.hmcts.net
    keyVaults:
      civil:
        resourceGroup: civil
        secrets:
          - civil-idam-client-secret
          - microservicekey-civil-service
          - system-update-user-username
          - system-update-user-password
          - cross-access-user-username
          - cross-access-user-password
          - prd-admin-user-username
          - prd-admin-user-password
          - docmosis-api-key
          - gov-notify-api-key
          - sendgrid-api-key
          - robotics-notification-sender
          - robotics-notification-recipient
          - robotics-notification-recipient-spec
          - name: launch-darkly-sdk-key-non-prod
            alias: launch-darkly-sdk-key
          - ordnance-survey-api-key
          - robotics-notification-multipartyrecipient
          - notification-caseworker-spec-receiver
    environment:
      LAUNCH_DARKLY_ENV: ${SERVICE_FQDN}
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
      SERVICE_REQUEST_UPDATE: https://${SERVICE_NAME}.preview.platform.hmcts.net/service-request-update
      SERVICE_REQUEST_UPDATE_CLAIM_ISSUED: https://${SERVICE_NAME}.preview.platform.hmcts.net/service-request-update-claim-issued
      EM_CCD_ORCHESTRATOR_URL: https://em-ccdorc-${SERVICE_FQDN}
ccd:
  ccd:
    elastic:
      enabled: true
  ccd-data-store-api:
    java:
      environment:
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOSTS: ${SERVICE_NAME}-es-master:9200
        ELASTIC_SEARCH_DATA_NODES_HOSTS: http://${SERVICE_NAME}-es-master:9200
  ccd-definition-store-api:
    java:
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${CCD_DEFINITION_STORE_S2S_SECRET}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOST: ${SERVICE_NAME}-es-master
        ELASTIC_SEARCH_CASE_INDEX_MAPPING_FIELDS_LIMIT: 10000
  elasticsearch:
    nameOverride: ${SERVICE_NAME}-es
    imageTag: "7.17.1"
    initResources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "25m"
        memory: "512Mi"
  logstash:
    resources:
      requests:
        cpu: "500m"
        memory: "1024Mi"
      limits:
        cpu: "2500m"
        memory: "1024Mi"
    configTpl:
      db.url: jdbc:postgresql://${SERVICE_NAME}-postgresql:5432/data-store?ssl=disable&stringtype=unspecified
      db.user: ${POSTGRES_USER}
      db.pwd: ${POSTGRES_PASSWORD}
      es.data.nodes.url: http://${SERVICE_NAME}-es-master:9200
    livenessProbe:
      initialDelaySeconds: 90

em-ccdorc:
  enabled: true
  java:
    image: hmctspublic.azurecr.io/em/ccdorc:latest
    releaseNameOverride: ${SERVICE_NAME}-em-ccdorc
    ingressHost: em-ccdorc-${SERVICE_FQDN}
    keyVaults:
      em-ccdorc:
        resourceGroup: em-ccdorc
        secrets:
          - name: microservicekey-em-ccd-orchestrator
            alias: S2S_KEY
          - name: notification-api-key
            alias: NOTIFICATION_API_KEY
          - name: app-insights-connection-string
            alias: app-insights-connection-string
    environment:
      CCD_DATA_API_URL: http://${SERVICE_NAME}-ccd-data-store-api
      CALLBACK_DOMAIN: em-ccdorc-${SERVICE_FQDN}
