civil-service:
  java:
    devcpuRequests: 50m
    devcpuLimits: 700m
    devmemoryRequests: 1536Mi
    devmemoryLimits: 2048Mi
    environment:
      DOCMOSIS_TORNADO_URL: https://docmosis.aat.platform.hmcts.net
