civil-ccd-stack:
  enabled: false
idam-pr:
  enabled: false
xui-webapp:
  enabled: false
camunda-bpm:
  enabled: false
civil-wa:
  enabled: false
servicebus:
  enabled: false
postgresql:
  enabled: false
civil-translation:
  enabled: false
ccd-def-cleanup:
  enabled: false
am-org-role-mapping-service:
  enabled: false
ccd-case-document-am-api:
  enabled: false
em-ccdorc:
  enabled: false
em-stitching:
  enabled: false
ccd-events-topic:
  enabled: false
